import { User, Recipe, RecipeRating, RecipeList, LeaderboardEntry } from '@/types';

export const currentUser: User = {
  id: 'u1',
  name: 'Alex Chen',
  username: 'alexcooks',
  avatar: 'https://i.pravatar.cc/150?img=11',
  bio: 'Home cook exploring global flavors. Pasta enthusiast.',
  followersCount: 234,
  followingCount: 189,
  recipesRated: 67,
};

export const users: User[] = [
  currentUser,
  {
    id: 'u2',
    name: 'Sarah Kim',
    username: 'sarahbakes',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Baker & pastry lover',
    followersCount: 512,
    followingCount: 302,
    recipesRated: 94,
  },
  {
    id: 'u3',
    name: 'Marcus Johnson',
    username: 'chefmarcus',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'BBQ master, southern comfort food',
    followersCount: 1243,
    followingCount: 456,
    recipesRated: 156,
  },
  {
    id: 'u4',
    name: 'Priya Patel',
    username: 'priyacooks',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Indian home cooking & spice explorer',
    followersCount: 876,
    followingCount: 234,
    recipesRated: 112,
  },
  {
    id: 'u5',
    name: 'Emma Wilson',
    username: 'emmaeats',
    avatar: 'https://i.pravatar.cc/150?img=20',
    bio: 'Healthy meals & meal prep queen',
    followersCount: 345,
    followingCount: 198,
    recipesRated: 45,
  },
];

export const recipes: Recipe[] = [
  {
    id: 'r1',
    name: 'Cacio e Pepe',
    cuisine: 'Italian',
    category: 'Pasta',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600',
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    difficulty: 'Medium',
    ingredients: ['Spaghetti', 'Pecorino Romano', 'Black pepper', 'Salt', 'Pasta water'],
    instructions: [
      'Bring a large pot of salted water to a boil',
      'Toast black pepper in a dry pan',
      'Cook pasta 1 minute less than package directions',
      'Combine cheese and pepper with pasta water',
      'Toss pasta in the sauce until creamy',
    ],
    averageRating: 9.2,
    totalRatings: 342,
  },
  {
    id: 'r2',
    name: 'Butter Chicken',
    cuisine: 'Indian',
    category: 'Curry',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600',
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Chicken thighs', 'Yogurt', 'Tomato sauce', 'Butter', 'Cream', 'Garam masala', 'Turmeric', 'Ginger', 'Garlic'],
    instructions: [
      'Marinate chicken in yogurt and spices for 1 hour',
      'Cook chicken in a hot pan until charred',
      'Simmer tomato sauce with butter and spices',
      'Add chicken and cream, cook 20 minutes',
      'Finish with butter and serve with naan',
    ],
    averageRating: 9.0,
    totalRatings: 567,
  },
  {
    id: 'r3',
    name: 'Sourdough Bread',
    cuisine: 'French',
    category: 'Bread',
    image: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=600',
    prepTime: 30,
    cookTime: 45,
    servings: 1,
    difficulty: 'Hard',
    ingredients: ['Bread flour', 'Sourdough starter', 'Water', 'Salt'],
    instructions: [
      'Mix flour, water, and starter. Autolyse 30 min',
      'Add salt and perform stretch & folds every 30 min',
      'Bulk ferment 4-6 hours at room temp',
      'Shape and cold proof overnight',
      'Bake in Dutch oven at 500°F then 450°F',
    ],
    averageRating: 8.8,
    totalRatings: 234,
  },
  {
    id: 'r4',
    name: 'Spicy Miso Ramen',
    cuisine: 'Japanese',
    category: 'Soup',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600',
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: 'Medium',
    ingredients: ['Ramen noodles', 'Miso paste', 'Chili oil', 'Pork belly', 'Soft-boiled egg', 'Green onions', 'Nori', 'Chicken broth'],
    instructions: [
      'Prepare broth with miso paste and chili',
      'Cook pork belly until caramelized',
      'Boil eggs for 6.5 minutes for jammy center',
      'Cook noodles according to package',
      'Assemble bowl with toppings',
    ],
    averageRating: 9.1,
    totalRatings: 445,
  },
  {
    id: 'r5',
    name: 'Classic Tiramisu',
    cuisine: 'Italian',
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600',
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Mascarpone', 'Eggs', 'Sugar', 'Espresso', 'Ladyfingers', 'Cocoa powder', 'Marsala wine'],
    instructions: [
      'Whip egg yolks and sugar until pale',
      'Fold in mascarpone until smooth',
      'Whip egg whites to stiff peaks and fold in',
      'Dip ladyfingers in espresso mixture',
      'Layer cream and ladyfingers, dust with cocoa',
    ],
    averageRating: 8.7,
    totalRatings: 289,
  },
  {
    id: 'r6',
    name: 'Thai Green Curry',
    cuisine: 'Thai',
    category: 'Curry',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Green curry paste', 'Coconut milk', 'Chicken', 'Thai basil', 'Bamboo shoots', 'Fish sauce', 'Palm sugar', 'Thai eggplant'],
    instructions: [
      'Fry curry paste in coconut cream until fragrant',
      'Add chicken and cook through',
      'Pour in remaining coconut milk',
      'Add vegetables and simmer 10 min',
      'Season with fish sauce and sugar, top with basil',
    ],
    averageRating: 8.9,
    totalRatings: 398,
  },
  {
    id: 'r7',
    name: 'NY-Style Pizza Dough',
    cuisine: 'American',
    category: 'Bread',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600',
    prepTime: 20,
    cookTime: 12,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Bread flour', 'Water', 'Yeast', 'Salt', 'Sugar', 'Olive oil'],
    instructions: [
      'Combine water, yeast, and sugar',
      'Mix in flour, salt, and olive oil',
      'Knead 10 minutes until smooth',
      'Cold ferment 24-72 hours',
      'Stretch and bake at highest oven temp',
    ],
    averageRating: 9.3,
    totalRatings: 512,
  },
  {
    id: 'r8',
    name: 'Crispy Tacos al Pastor',
    cuisine: 'Mexican',
    category: 'Tacos',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Pork shoulder', 'Pineapple', 'Achiote paste', 'Corn tortillas', 'Onion', 'Cilantro', 'Lime'],
    instructions: [
      'Marinate pork in achiote and pineapple juice',
      'Grill or broil pork until charred',
      'Grill pineapple slices',
      'Warm tortillas on a comal',
      'Assemble with onion, cilantro, and lime',
    ],
    averageRating: 9.4,
    totalRatings: 623,
  },
];

export const feedRatings: RecipeRating[] = [
  {
    id: 'fr1',
    user: users[1],
    recipe: recipes[0],
    rating: 9.0,
    notes: 'The simplicity of this dish is what makes it incredible. Key is the pasta water!',
    favoritePart: 'The creamy pepper sauce',
    withUsers: [users[4]],
    likes: 12,
    comments: 3,
    liked: true,
    timestamp: '5 minutes ago',
  },
  {
    id: 'fr2',
    user: users[2],
    recipe: recipes[7],
    rating: 9.5,
    notes: 'Best tacos I\'ve ever made at home. The achiote marinade is a game changer.',
    favoritePart: 'Charred pineapple topping',
    likes: 24,
    comments: 7,
    liked: false,
    timestamp: '15 minutes ago',
  },
  {
    id: 'fr3',
    user: users[3],
    recipe: recipes[1],
    rating: 8.5,
    notes: 'My go-to butter chicken recipe. Restaurant quality at home!',
    favoritePart: 'Rich tomato-butter sauce',
    withUsers: [users[0]],
    likes: 18,
    comments: 5,
    liked: false,
    timestamp: '1 hour ago',
  },
  {
    id: 'fr4',
    user: users[4],
    recipe: recipes[3],
    rating: 9.0,
    notes: 'Perfect for a cold night. The spicy miso broth is addictive.',
    likes: 8,
    comments: 2,
    liked: true,
    timestamp: '2 hours ago',
  },
  {
    id: 'fr5',
    user: users[1],
    recipe: recipes[4],
    rating: 8.0,
    notes: 'Made this for a dinner party and everyone loved it. Make it a day ahead!',
    favoritePart: 'Mascarpone cream layer',
    likes: 15,
    comments: 4,
    liked: false,
    timestamp: '3 hours ago',
  },
  {
    id: 'fr6',
    user: users[2],
    recipe: recipes[2],
    rating: 7.5,
    notes: 'Took me 3 attempts to get right but so worth the effort.',
    favoritePart: 'That ear and crust',
    likes: 31,
    comments: 11,
    liked: true,
    timestamp: '5 hours ago',
  },
];

export const featuredLists: RecipeList[] = [
  {
    id: 'fl1',
    title: 'Ultimate Pasta Bucket List',
    description: 'Every pasta dish you need to master',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600',
    recipes: [recipes[0], recipes[4]],
    createdBy: users[2],
    userProgress: { tried: 3, total: 8 },
  },
  {
    id: 'fl2',
    title: 'Best Weeknight Dinners',
    description: 'Quick and delicious meals under 30 min',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600',
    recipes: [recipes[5], recipes[3]],
    createdBy: users[3],
    userProgress: { tried: 5, total: 12 },
  },
  {
    id: 'fl3',
    title: 'Around the World in 10 Dishes',
    description: 'Global flavors from your kitchen',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600',
    recipes: [recipes[1], recipes[5], recipes[7]],
    createdBy: users[1],
    userProgress: { tried: 2, total: 10 },
  },
  {
    id: 'fl4',
    title: 'Bread Baker\'s Guide',
    description: 'From beginner loaves to artisan breads',
    image: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=600',
    recipes: [recipes[2], recipes[6]],
    createdBy: users[4],
    userProgress: { tried: 1, total: 6 },
  },
];

export const userLists: RecipeList[] = [
  {
    id: 'ul1',
    title: 'My Favorites',
    description: 'Recipes I keep coming back to',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600',
    recipes: [recipes[0], recipes[1], recipes[3], recipes[7]],
    createdBy: currentUser,
  },
  {
    id: 'ul2',
    title: 'Date Night',
    description: 'Impressive dishes for special occasions',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600',
    recipes: [recipes[0], recipes[4]],
    createdBy: currentUser,
  },
  {
    id: 'ul3',
    title: 'Want to Try',
    description: 'On my cooking bucket list',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600',
    recipes: [recipes[2], recipes[5], recipes[6]],
    createdBy: currentUser,
  },
];

export const leaderboardData: LeaderboardEntry[] = recipes
  .sort((a, b) => b.averageRating - a.averageRating)
  .map((recipe, index) => ({
    rank: index + 1,
    recipe,
    averageRating: recipe.averageRating,
    totalRatings: recipe.totalRatings,
    cuisine: recipe.cuisine,
  }));

export const cuisineFilters = [
  'All',
  'Italian',
  'Japanese',
  'Indian',
  'Thai',
  'Mexican',
  'American',
  'French',
];

export const categoryFilters = [
  'All',
  'Pasta',
  'Curry',
  'Soup',
  'Bread',
  'Dessert',
  'Tacos',
];
